name: SmartC Tests

on: [ push ]

jobs:
  build-smartc:
    name: Test and Build SmartC
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Run SmartC Tests
        working-directory: ./
        run: |
          npm ci
          npm run test:ci

      - name: fix code coverage paths
        working-directory: ./coverage
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
